[psql]
# TODO: should be yanis
#dsn = "host=db port=5432 user=yanis password=yanis dbname=events sslmode=disable"
dsn = "host=db port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

[logger]
path = "./logs/logs.txt"

[queue]
consumerTag = "events_consumer"
uri = "amqp://guest:guest@queue/"
exchangeName = "exchange"
exchangeType = "direct"
queue = "events_notifications"
bindingKey = "events"

[grpcServer]
address = "web:9000"

[httpServer]
address = "web:8080"

[scheduler]
fetchIntervalSeconds = 5