
// Code generated by cool go-validate tool; DO NOT EDIT.
package models

func (x User) Validate() ([]ValidationError, error) {
    errs := make([]ValidationError, 1) 
if (x.Age < 18) {
	errs = append(errs, ValidationError{Field: "Age", Err: "Should be more than 18"})
}

if (x.Age > 50) {
	errs = append(errs, ValidationError{Field: "Age", Err: "Should be less than 50"})
}


	return errs, nil
}
